version: "2"
services:
  mongo:
    container_name: mongo_db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
 
  app:
    container_name: backk
    restart: always
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    