version: "2"
services:
  mongo:
    container_name: mongo_db
    image: mongo:5.0
    restart: always
    ports:
      - "27027:27027"
    volumes:
      - mongodb_data:/data/db
 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backk
    restart: always
    ports:
      - "127.0.0.1:5050:5050"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

volumes:
  mongodb_data:
  