version: "3"
services:
  mongo:
    container_name: mongo_db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
      
  app:
    container_name: backend
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
